language: java
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
after_success:
- codecov
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_deploy:
- "./gradlew releaseZip"
deploy:
  provider: heroku
  api_key:
    secure: VSMbnaX+P3ef24aXdjrySy95RX5hr4gktuaz8I75i/pkTdp8WrvO4VDZZ0jNF85P7dgjVJUNymRg/tbcd42HUJGTt3TXvCM0ptS2ec97n12j983ICI0HwwUf1WJRuAKf0YGNi/ja8sWdgwAJHajHCqE2uVXSDTASxVQrQC9xOvkbC/8bPeGs4nn6LbXJLP8/VFuFbLnumhl/WqnhbjAJFPcIkICcswCZGTMvk9yVknWZJ0+pyzTw7qB5DRwVVpsXyY7ryofzI+PoJI8xFSOivudsXddS2zcQyo3mqfQ+gDW/Br5p+KzZu2JgsByRXmV3MAVNq2AG3+Gv617kxg8Iz3ce70h7QeduWSdIOPTimuUZSG7x2ntlbGzj7JMDzCNQbyaseyMWVCpfoXXSm0IXQhq0qJ1iDwV0aw/QxmBI6vZgwJnq7f3WBb7o9Pv+7HptJ3qoOUSUBT29mbAA/9l8infp/2X4ywQEe121h/Cqp9tm8n1jdR1z9eBcVBXLaThxkc3hQNv3Ie0hRKVeN/ApbSe64RpBi3IKlD6BBHhJ9kn+6JsWGVzYoJp+AY3BvVXz2WeXqPEZj7z9Skbu9mq4eK/XP+/y3m+HNMsM5hKjrRUVEImMr2wmoS8DfGteDTNNDUd8l/NXhFQjQhD1264A7Xcjd+dlNy2s859pOvNmMZQ=
  app: bprzybylski-jalgoarena-submiss
  on:
    repo: bartpr/JAlgoArena-Submissions
